apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-qgz4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-qgz4
    app.kubernetes.io/part-of: tkrw-pr712-0075-0057-app
  name: devfile-sample-qgz4
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-qgz4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-qgz4
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0057-tenant/tkrw-pr712-0075-0057-app/devfile-sample-qgz4@sha256:bae98cc0b1d3ad29e846eab13929e831ff45ff228b3c947d108e6ce11315f11a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
